engines:
  rubocop:
    enabled: true
  reek:
    enabled: false
  duplication:
    enabled: false
  markdownlint:
    enabled: false
  fixme:
    enabled: false
ratings:
   paths:
   - Gemfile.lock
   - "**.rb"
   - "**.md"

exclude_paths:
- "pkg/*"
- "old/*"
- "spec/*"
- "tests/*"
- "example_tests/*"
- "example_scripts/*"
- ".vscode/*"
- "backup/*"
- "bin/*"

