
# SDK requires some methods to include higher amounts of parameters
Metrics/ParameterLists:
  Enabled: true
  Max: 12


Style/IndentationWidth:
  Enabled: false

# Some of the methods are schema checkers and require
# extremely long schema declarations.
Metrics/LineLength:
  Enabled: true
  Max: 166

Metrics/MethodLength:
  Enabled: true
  Max: 90

# Due to the presence of global API keys, this is disabled.
Style/GlobalVars:
  Enabled: false

# Indentation of comments.
Style/CommentIndentation:
  Enabled: false

# ! Checks trailing blank lines and final newline.
Style/TrailingBlankLines:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/StringLiters:
   Enabled: false

Style/IndentHash:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/IndentAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceievedComplexity:
  Enabled: false